//package information
package AdditionalScenes;
//imports
import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextArea;
import javafx.stage.Stage;
import seng300.Seng300;

/**
 * FXML Controller class
 *
 * @author Noah
 */
public class StudentApplicationViewController implements Initializable {
    //instance variables
    @FXML
    private Button backButton;
    @FXML
    private Button acceptButton;
    @FXML
    private Button withdrawButton;
    @FXML
    private ScrollPane scrollWindow;
    @FXML
    private TextArea applicationInfo;

    /**
     * Initializes the controller class.
     */
    @Override
    public void initialize(URL url, ResourceBundle rb) {
        this.applicationInfo.setText(Seng300.theManager.getCurrentApplication().toString());
    }    
    /**
     * This method takes us back to the student main page from the view application page
     * @param event mouse event generated by clicking the back button
     * @throws IOException 
     */
    @FXML
    private void backToViewApplications(ActionEvent event) throws IOException{
        Parent root = FXMLLoader.load(getClass().getResource("/seng300/studentMainPage.fxml"));
        Scene sc = new Scene(root);
        Stage s = Seng300.mainStage; 
        s.setTitle("Home");
        s.setScene(sc);
        s.show();
    }
    /**
     * this method accepts the scholarship if it has been granted to a student
     * @param event mouse event generated by clicking the accept button
     */
    @FXML
    private void accept(ActionEvent event) {
        
    }
    /**
     * this method withdraws the student's application for the scholarship
     * @param event mouse event generated by clicking the withdraw button
     */
    @FXML
    private void withdraw(ActionEvent event) {
        
    }

    
    
}
